### ISSUE TITLE
BaseARN does not generate valid ARNs for region-less resources in China

### ISSUE THREAD

**Issue by mxpxgx** [cloudtools/awacs#101]
This is related to #84
S3 bucket ARN cannot contain region information, and the current implementation to generate the ARN partition is based on the region which should not be specified.

This is an issue for buckets in China region (_e.g._ cn-north-1).

This is an example of a valid China bucket: arn:aws-cn:s3:::my_china_bucket

This affects any region-less services like S3 and IAM in China accounts.

aws_partition should be at least optional.
```
def __init__(self, service, resource, region='', account='', aws_partition=''):
    region_string = region.lower()
    if not aws_partition:
        if region_string.startswith("cn-"):
            aws_partition = "aws-cn"
        elif region_string.startswith("us-gov"):
            aws_partition = "aws-us-gov"
        else:
            aws_partition = "aws"

    self.data = "arn:%s:%s:%s:%s:%s" % (
        aws_partition, service, region, account, resource)
```

**Comment by markpeek** [comment]
Fixed via #103
