### ISSUE TITLE
Wrong Condition name in `_condition_strings`

### ISSUE THREAD

**Issue by iharush** [cloudtools/awacs#111]
The `_condition_strings` has some wrong condition name value:
`StringEqualsIgnoresCase` should be `StringEqualsIgnoreCase` (without the s in Ignore)

in addition the condition `StringNotEqualsIgnoreCase` is missing.

**Comment by iharush** [comment]
From AWS  Iam console:

![image](https://user-images.githubusercontent.com/6792346/52797843-641b4780-307f-11e9-8c85-53860ccca0b2.png)

**Comment by markpeek** [comment]
Fixed via #112
