### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by craigbruce** [cloudtools/awacs#12]
Hi, 

I don't suppose you could release a new version? There are quite a few new services only on master, like SWF.

Cheers
Craig

**Comment by phobologic** [comment]
Hey Craig - I'll try to take a look at getting this out tonight.

**Comment by phobologic** [comment]
MAYBE tomorrow at the latest.

**Comment by craigbruce** [comment]
Excellent - thanks very much :)

**Comment by markpeek** [comment]
Or maybe just now...0.5.0 has been released. Thanks for the reminder Craig.
