### ISSUE TITLE
PRs

### ISSUE THREAD

**Issue by marinpurgar** [cloudtools/awacs#121]
Any chance to give some luv to current PRs?

**Comment by markpeek** [comment]
Yes, I hope to have time later this evening to go through the PR's. I had asked a question last night for this [PR](https://github.com/cloudtools/awacs/pull/115#issuecomment-483468671) to get more clarity.

**Comment by marinpurgar** [comment]
Thanx! Closing the issue. Sry for spamming.

**Comment by markpeek** [comment]
Not spam at all. Always good to the need a new release done since it means people are using it. :-)

**Comment by markpeek** [comment]
awacs 0.9.0 has been released.
