### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by gcochard** [cloudtools/awacs#147]
We're using KMS asymmetric keys to sign and we'd like to add permissions programmatically. It appears the current `0.9.8` version was released in February and KMS was updated to include `Sign` a week ago. Can you please cut a new release so we can incorporate this?

Thanks!

**Comment by markpeek** [comment]
Yes, I'll add it to my todo list for over the weekend. @michael-k do you want to add anything more prior to a release?

**Comment by michael-k** [comment]
Sure; here are a bunch of new actions: cloudtools/awacs#148

**Comment by markpeek** [comment]
@gcochard just pushed a new [release 0.9.9](https://github.com/cloudtools/awacs/releases/tag/0.9.9). @michael-k thank you for the quick turn on the updates!
