### ISSUE TITLE
Add support for eks-auth:AssumeRoleForPodIdentity

### ISSUE THREAD

**Issue by skeggse** [cloudtools/awacs#268]
AWS has a relatively [new service prefix](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoneksauth.html) (`eks-auth`) that exposes a single action. It'd be great to have this in `awacs`!

**Comment by skeggse** [comment]
Submitted #269 to fix this particular issue; it looks like the automated process for pulling new definitions hasn't succeeded in a few weeks due to https://github.com/cloudtools/awacs/pull/269/files#r1435317404

**Comment by markpeek** [comment]
Fixed via the scrape.py change in your PR #269.
