### ISSUE TITLE
invalid permission?

### ISSUE THREAD

**Issue by stan3** [cloudtools/awacs#34]
awacs/sqs.py lists ChangeMessageVisibilityBatch as a permission but if I try and use it in a queue policy manually I get:

> Failed to save changes to the policy document. Reason: com.amazonaws.AmazonServiceException: Value SQS:ChangeMessageVisibilityBatch for parameter ActionName is invalid. Reason: Please refer to the appropriate WSDL for a list of valid actions. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; 

The WSDL at http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl doesn't seemed to clarify (as ChangeMessageVisibilityBatch is listed) but I don't fully understand it.  But it seems like ChangeMessageVisibilityBatch isn't valid, and it is not listed on http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/UsingIAM.html.

**Comment by markpeek** [comment]
I'd suggest filing a bug with AWS on this issue. From the [docs](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibilityBatch.html) it looks like a valid action. Also, the actions in awacs are generated from AWS policy data (via tools/gen.py) and the last time I ran it that [action](https://github.com/cloudtools/awacs/blob/python26_and_updates/awacs/sqs.py#L36) was still present.

**Comment by stan3** [comment]
Ah, I mean to indicate it appears to be an invalid permission but still a valid action (I assume the sqs:ChangeMessageVisibility permission covers both).

**Comment by stan3** [comment]
further from http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/UsingIAM.html
> The specific actions you could grant permission for were a subset of the overall set of Amazon SQS actions.

So it would appear as though DeleteMessageBatch, AddPermission, RemovePermission etc would similarly be invalid permissions but valid actions.

Perhaps permissions should not be represented here though?

**Comment by stan3** [comment]
any feedback on this? thanks

**Comment by markpeek** [comment]
We'll have to take a look on whether we can determine the valid subset. I'll reopen for now.

**Comment by RyPeck** [comment]
@stan3 you are correct. Here are the docs on the valid subset.

> Specifying SendMessage, DeleteMessage, or ChangeMessageVisibility for ActionName.n also grants permissions for the corresponding batch versions of those actions: SendMessageBatch, DeleteMessageBatch, and ChangeMessageVisibilityBatch.
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_AddPermission.html

**Comment by markpeek** [comment]
Fixed in recent updates. Thanks for the issue.
