### ISSUE TITLE
Missing autoscaling permissions for "AttachLoadBalancers" and "DetachLoadBalancers"

### ISSUE THREAD

**Issue by matthewdfuller** [cloudtools/awacs#41]
The autoscaling.py file is missing the following lines:

```
AttachLoadBalancers = Action(prefix, 'AttachLoadBalancers'),
DetachLoadBalancers = Action(prefix, 'DetachLoadBalancers')
```

These were actually missing from the AWS console until recently due to an oversight on their end. They have always been valid permissions, but just didn't exist in the "IAM Role Generator" UI. I filed a support request with AWS and they added them.

**Comment by craigbruce** [comment]
This is fixed in PR #40
