### ISSUE TITLE
iam ARN broken

### ISSUE THREAD

**Issue by webratz** [cloudtools/awacs#54]
Hi,

at least in the lates t(0.6.0) version the IAM ARN function returns something else than in `0.5.4``
. This is no more a valid ARN, therefore I consider this function broken in the new version.
## test code

```
import awacs.iam
foo_arn = awacs.iam.ARN('123456789012', 'root')
print foo_arn.data
```
### 0.5.4

this is an valid ARN

```
$ python test.py
arn:aws:iam::123456789012:root
```
### 0.6.0

this ARN is invalid

```
$ python test.py
arn:aws:iam:root::123456789012
```

**Comment by markpeek** [comment]
My apologies for the breakage. We had hoped to make ARN usage more consistent across all of the resource types. This was introduced in 8aed5cc5 and further changes in 0.6.0 to allow for better generated code. @phobologic and @mhahn, do you have any comments about this?

The workaround and potentially the longer term fix would be to use one of these forms:
```
>>> import awacs.iam
>>> awacs.__version__
'0.6.0'
>>> awacs.iam.ARN(account='123456789012', resource='root').data
'arn:aws:iam::123456789012:root'
>>> awacs.iam.ARN('root', '', '123456789012').data
'arn:aws:iam::123456789012:root'
```

**Comment by webratz** [comment]
Probably the old behaviour should be restored, but adding a deprecation message.
After a while then switching over to the current behaviour

**Comment by drandyziegler** [comment]
Looks like the same problem exists with awacs.sns.ARN()

**Comment by ntwaddell** [comment]
How can I do this with Troposphere?   Principal=Principal("AWS", [IAM_ARN(account=Ref('AWS::AccountId'), resource='role/Administrators')]),

**Comment by emayssat-ms** [comment]
@ntwaddell, you can't. AWACS regenerate a template, which is reused (as a string) by troposphere.
In other words, Ref in AWACS are not supported. Instead use troposphere's Join!

**Comment by phobologic** [comment]
Closing this - after all these years, people should have switched over if using this.
