### ISSUE TITLE
Missing ForAllValues / ForAnyValue 

### ISSUE THREAD

**Issue by troyready** [cloudtools/awacs#56]
As documented in https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html - should be possible to make a condition like:

``` json
"Condition": {
  "ForAllValues:StringLike": {
    "dynamodb:requestedAttributes": [
      "PostDateTime",
      "Message",
      "Tags"
    ]
  }
}
```

Seem valuable to anyone else to add?

**Comment by ceaess** [comment]
I'd find this valuable.
