### ISSUE TITLE
Need support for Amazon Cognito User Pools

### ISSUE THREAD

**Issue by philipmw** [cloudtools/awacs#62]
[IAM Policy Generator](https://awspolicygen.s3.amazonaws.com/policygen.html) supports "Amazon Cognito User Pools", having these actions:

* cognito-idp:AddCustomAttributes
* cognito-idp:AdminAddUserToGroup
* cognito-idp:AdminConfirmSignUp
* cognito-idp:AdminCreateUser
* cognito-idp:AdminDeleteUser
* cognito-idp:AdminDeleteUserAttributes
* cognito-idp:AdminDisableUser
* cognito-idp:AdminEnableUser
* cognito-idp:AdminForgetDevice
* cognito-idp:AdminGetDevice
* cognito-idp:AdminGetUser
* cognito-idp:AdminInitiateAuth
* cognito-idp:AdminListDevices
* cognito-idp:AdminListGroupsForUser
* cognito-idp:AdminRemoveUserFromGroup
* cognito-idp:AdminResetUserPassword
* cognito-idp:AdminRespondToAuthChallenge
* cognito-idp:AdminSetUserSettings
* cognito-idp:AdminUpdateDeviceStatus
* cognito-idp:AdminUpdateUserAttributes
* cognito-idp:AdminUserGlobalSignOut
* cognito-idp:CreateGroup
* cognito-idp:CreateUserImportJob
* cognito-idp:CreateUserPool
* cognito-idp:CreateUserPoolClient
* cognito-idp:DeleteGroup
* cognito-idp:DeleteUserPool
* cognito-idp:DeleteUserPoolClient
* cognito-idp:DescribeUserImportJob
* cognito-idp:DescribeUserPool
* cognito-idp:DescribeUserPoolClient
* cognito-idp:GetCSVHeader
* cognito-idp:GetGroup
* cognito-idp:ListGroups
* cognito-idp:ListUserImportJobs
* cognito-idp:ListUserPoolClients
* cognito-idp:ListUserPools
* cognito-idp:ListUsers
* cognito-idp:ListUsersInGroup
* cognito-idp:StartUserImportJob
* cognito-idp:StopUserImportJob
* cognito-idp:UpdateGroup
* cognito-idp:UpdateUserPool
* cognito-idp:UpdateUserPoolClient

(source: IAM Policy Generator JS source code.)

We need support for this in awacs.

**Comment by markpeek** [comment]
I just ran an update and pushed to master which should have this change. Let me know if that works for you and I'll create a new release with it.

**Comment by philipmw** [comment]
Wow, what fast response! I will check in about an hour.

How do you track these changes? I looked at the IAM Policy Generator's source code, but surely there is a more authoritative and convenient way.

**Comment by markpeek** [comment]
I wish there was a more formal definition from AWS but I rely on pulling the policy generator code from the web assets and generating it from there. Code is [here](https://github.com/cloudtools/awacs/blob/master/tools/gen.py).

**Comment by philipmw** [comment]
Yes, this works for my purposes. Eagerly awaiting a release! Thanks!

**Comment by markpeek** [comment]
Thanks for the info on new services being available. Release 0.6.2 should now be available.
