### ISSUE TITLE
Missing a few CodeCommit & CloudFormation actions

### ISSUE THREAD

**Issue by Noah-Huppert** [cloudtools/awacs#70]
I was going recreating [this AWS policy example](https://docs.aws.amazon.com/codepipeline/latest/userguide/iam-identity-based-access-control.html#view-default-service-role-policy) with Troposphere and awacs and I found that awacs was missing a couple actions.

- `codecommit:CancelUploadArchive`
- `codecommit:GetCommit`
- `codecommit:GetUploadArchiveStatus`
- `codecommit:UploadArchive`
- `cloudformation:DeleteChangeSet`

More may be missing, I didn't look at the spec, these actions just weren't implemented and I was trying to use them.

**Comment by markpeek** [comment]
Added. Thanks for the issue.
