### ISSUE TITLE
cloudfront does not allow for resource level permissions

### ISSUE THREAD

**Issue by parrott-kevin** [cloudtools/awacs#75]
When creating policies for cloudfront, resource level specifications are [not allowed](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html) and [example](https://forums.aws.amazon.com/thread.jspa?messageID=755009&tstart=0). So when creating policies the creator has to remember to change
```
"Resource": [
    "arn:aws:cloudfront:::*"
]
```
to 
```
"Resource": [
    "*"
]
```
for the policy to be correct.

**Comment by michael-k** [comment]
> resource level specifications are not allowed

This is no longer the case.
