### ISSUE TITLE
Generated policies are missing some dynamo Actions

### ISSUE THREAD

**Issue by pdex** [cloudtools/awacs#90]
It appears that the policies.js bundle that's being parsed to generate the .py files is missing some dynamo actions. Specifically dynamodb:DescribeTimeToLive and dynamodb:UpdateTimeToLive.

This page appears to be missing `UpdateTimeToLive`
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_dynamodb.html

This page maybe has the most correct set of references?
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/api-permissions-reference.html

It might make sense for the `gen.py` process to reconcile the policies.js source against some of the html documentation. I'd be willing to take a crack at that with a pull request if you're interested.

**Comment by markpeek** [comment]
I just pushed an override to include those into the generated dynamodb file. Give it a look and see if that works for you.

**Comment by pdex** [comment]
LGTM 👍
