### ISSUE TITLE
Is it possible to get a release?

### ISSUE THREAD

**Issue by hammy7867** [cloudtools/awacs#95]
Hello,

There were some upates added for a few missing permissions that I opened an issue for about a month back. I'm hoping we can get a release with these changes?

Thanks!

**Comment by matt-land** [comment]
bump. We would like to use secrets manager actions from awacs.

**Comment by scionaltera** [comment]
Bump again. I’d like to get my PRs merged and released so we can use QuickSight.

**Comment by markpeek** [comment]
ack...let me take a look later today and see if I can get a release out tonight.

**Comment by markpeek** [comment]
Release 0.8.2 was just pushed out.
